/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    MyLikeList: typeof import('./src/components/MyLikeList.vue')['default']
    Notice: typeof import('./src/components/icon/Notice.vue')['default']
    QQLogin: typeof import('./src/components/icon/QQLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamList: typeof import('./src/components/TeamList.vue')['default']
    UserCommentList: typeof import('./src/components/UserCommentList.vue')['default']
    UserLikeList: typeof import('./src/components/UserLikeList.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    VanTimePicker: typeof import('vant/es')['TimePicker']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
